version: '2'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
      - network.publish_host=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 3g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9300
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    mem_limit: 1g
    ports:
      - 5601:5601
    depends_on:
      - "elasticsearch"
    links:
      - "elasticsearch"

  daon-manager:
    image: daon-manager
    environment:
      - "JAVA_OPTS=-Xms8g -Xmx8g"
      - SEVER_PORT=8001
    mem_limit: 9g
    ports:
      - 8001:8001
    depends_on:
      - "elasticsearch"
    links:
      - "elasticsearch"

volumes:
  esdata:
    driver: local