version: '2'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    environment:
      - "cluster.name=elasticsearch"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "xpack.security.enabled=false"
      - "network.publish_host=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 3g
    volumes:
      - /Users/mac/esdata:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9300
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    environment:
    expose:
      - 5601
    ports:
      - 5601:5601
    depends_on:
      - "elasticsearch"
    links:
      - "elasticsearch"

  daon-manager:
    image: daon-manager
    mem_limit: 6g
    ports:
      - 5001:5001
    command:
      ["java", "-Xms1g", "-Xmx1g", "-jar", "app.jar", "--es.clusterNodes=elasticsearch:9300"]
    depends_on:
      - "elasticsearch"
    links:
      - "elasticsearch"
