spring:
  application:
    name: DaonManager

server:
  port: 5001

management:
  security:
    enabled: false

endpoints:
  enabled: false

es:
  clusterNodes: localhost:9300
  cluster: elasticsearch

spark:
  home: /Users/mac/work/tools/spark-2.1.0-bin-hadoop2.7
  appResource: /Users/mac/IdeaProjects/daon/daon-dictionary/build/libs/daon-dictionary-all.jar
  master: local[*]