spring:
  application:
    name: DaonManager

server:
  port: 5001

management:
  security:
    enabled: false

endpoints:
  enabled: false

es:
  clusterNodes: daon.es:9300
  cluster: elasticsearch

spark:
#  home: /app/spark-2.2.0
#  appResource: /app/daon-dictionary.jar
  home: /Users/mac/work/tools/spark-2.1.0-bin-hadoop2.7
  appResource: /Users/mac/IdeaProjects/daon/docker/daon-manager/daon-dictionary-all.jar
  master: spark://daon.spark:7077
#  master: local[*]