spring:
  application:
    name: DaonManager
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

server:
  port: 5001

management:
  security:
    enabled: false

endpoints:
  enabled: false

es:
  transportNodes: elasticsearch:9300
  httpNodes: elasticsearch:9200
  cluster: elasticsearch