spring:
  application:
    name: DaonManager

server:
  port: 5001

management:
  security:
    enabled: false

endpoints:
  enabled: false

es:
  transportNodes: elasticsearch:9300
  httpNodes: elasticsearch:9200
  cluster: elasticsearch

spark:
  master: local[*]