spring:
  application:
    name: DaonManager
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

server:
  port: 5001

management:
  endpoints:
    enabled-by-default: false

es:
  transportNodes: elasticsearch:9300
  httpNodes: elasticsearch:9200
  cluster: elasticsearch