spring:
  application:
    name: DaonManager

server:
  port: 5001

management:
  security:
    enabled: false

endpoints:
  enabled: false

es:
  transportNodes: elasticsearch:9300
  httpNodes: elasticsearch:9200
  cluster: elasticsearch

spark:
  home: /app/spark-2.2.0
  appResource: /app/daon-spark-all.jar
#  master: spark://daon.spark:7077
  master: local[*]