spring:
  application:
    name: DaonManager

server:
  port: 8080

management:
  security:
    enabled: false

endpoints:
  enabled: false

es:
  clusterNodes: daon.es:9300
  cluster: elasticsearch

spark:
  home: /app/spark-2.1.0
  appResource: /app/daon-dictionary-all.jar
  master: spark://daon.spark:7077